#!/usr/bin/python
import os

for i in range(1400,9000,200):

  # gen from fit to data ##
  cmd_gen1 = "python create_datacard.py --histpdfSig --fitDat -m "+str(i)+" --lumi 2000 --lumi_in 1769 -n genFit_dataJECV6  -o /cmshome/gdimperi/Dijet/CMSDIJETrepo/CMSSW_7_1_5/src/StatisticalTools/datacards_biasStudy_Spring15/  --inputSig /cmshome/gdimperi/Dijet/CMSDIJETrepo/CMSSW_7_1_5/src/StatisticalTools/inputs/ResonanceShapes_qg_13TeV_PU30_Spring15.root --inputData /cmshome/gdimperi/Dijet/CMSDIJETrepo/CMSSW_7_4_3_Dijet/src/CMSDIJET/DijetRootTreeAnalyzer/scripts/plots_data4T_Run2015D_DCSonly_1769pb-1_JEC_Summer15_25nsV6_withSF/histo_data_mjj_fromTree.root --inputBkg /cmshome/gdimperi/Dijet/CMSDIJETrepo/CMSSW_7_4_3_Dijet/src/CMSDIJET/DijetRootTreeAnalyzer/scripts/plots_data4T_Run2015D_DCSonly_1769pb-1_JEC_Summer15_25nsV6_withSF/histo_data_mjj_fromTree.root"
  ## gen from histogram template QCD ##
  cmd_gen2 = "python create_datacard.py --histpdfSig --histpdfBkg -m "+str(i)+" --lumi 2000 --lumi_in 1769 -n genMChist  -o /cmshome/gdimperi/Dijet/CMSDIJETrepo/CMSSW_7_1_5/src/StatisticalTools/datacards_biasStudy_Spring15/  --inputSig /cmshome/gdimperi/Dijet/CMSDIJETrepo/CMSSW_7_1_5/src/StatisticalTools/inputs/ResonanceShapes_qg_13TeV_PU30_Spring15.root --inputData /cmshome/gdimperi/Dijet/CMSDIJETrepo/CMSSW_7_4_3_Dijet/src/CMSDIJET/DijetRootTreeAnalyzer/scripts/plots_data4T_Run2015D_DCSonly_1769pb-1_JEC_Summer15_25nsV6_withSF/histo_data_mjj_fromTree.root --inputBkg /cmshome/gdimperi/Dijet/CMSDIJETrepo/CMSSW_7_4_3_Dijet/src/CMSDIJET/DijetRootTreeAnalyzer/scripts/plots_data4T_Run2015D_DCSonly_1769pb-1_JEC_Summer15_25nsV6_withSF/histo_data_mjj_fromTree.root"
  ## fit  ##
  cmd_fit = "python create_datacard.py --histpdfSig --fitDat -m "+str(i)+" --lumi 2000 --lumi_in 1769  -n toFit  -o /cmshome/gdimperi/Dijet/CMSDIJETrepo/CMSSW_7_1_5/src/StatisticalTools/datacards_biasStudy_Spring15/ --inputSig /cmshome/gdimperi/Dijet/CMSDIJETrepo/CMSSW_7_1_5/src/StatisticalTools/inputs/ResonanceShapes_qg_13TeV_PU30_Spring15.root --inputData /cmshome/gdimperi/Dijet/CMSDIJETrepo/CMSSW_7_4_3_Dijet/src/CMSDIJET/DijetRootTreeAnalyzer/scripts/plots_data4T_Run2015D_DCSonly_1769pb-1_JEC_Summer15_25nsV6_withSF/histo_data_mjj_fromTree.root --inputBkg /cmshome/gdimperi/Dijet/CMSDIJETrepo/CMSSW_7_4_3_Dijet/src/CMSDIJET/DijetRootTreeAnalyzer/scripts/plots_data4T_Run2015D_DCSonly_1769pb-1_JEC_Summer15_25nsV6_withSF/histo_data_mjj_fromTree.root"
  
  
#for i in range(2200,2400,200):
####old bias study############
#  cmd = "python create_datacard.py --histpdfSig --histpdfBkg -m "+str(i)+" --lumi 1000 -n genHistBkg_1100to4000 --sigEff 1. --sigXS "+str(sigXStimesA[i])+"  -o /cmshome/gdimperi/Dijet/CMSDIJETrepo/CMSSW_7_2_1_combine/src/CMSDIJET/StatisticalTools/datacards_pseudodatasetDinko_fitData/  --inputSig /cmshome/gdimperi/Dijet/CMSDIJETrepo/CMSSW_7_2_1_DiJet/src/CMSDIJET/DijetRootTreeMaker/test/Resonance_Shapes_qg_PU20_13TeV_newJEC.root --inputData /cmshome/gdimperi/Dijet/CMSDIJETrepo/CMSSW_7_2_1_DiJet/src/CMSDIJET/DijetRootTreeAnalyzer/test_fit/dijetFitResults_FuncType0_nParFit4_MC_1fb-1_Dinko.root --inputBkg /cmshome/gdimperi/Dijet/CMSDIJETrepo/CMSSW_7_2_1_DiJet/src/CMSDIJET/DijetRootTreeAnalyzer/scripts/histo_bkg_mjj.root"
#  cmd = "python create_datacard.py --histpdfSig --fitDat -m "+str(i)+" --lumi 1000 -n toFit_1100to4000 --sigEff 1. --sigXS "+str(sigXStimesA[i])+"  -o /cmshome/gdimperi/Dijet/CMSDIJETrepo/CMSSW_7_2_1_combine/src/CMSDIJET/StatisticalTools/datacards_pseudodatasetDinko_fitData/ --inputSig /cmshome/gdimperi/Dijet/CMSDIJETrepo/CMSSW_7_2_1_DiJet/src/CMSDIJET/DijetRootTreeMaker/test/Resonance_Shapes_qg_PU20_13TeV_newJEC.root --inputData /cmshome/gdimperi/Dijet/CMSDIJETrepo/CMSSW_7_2_1_DiJet/src/CMSDIJET/DijetRootTreeAnalyzer/test_fit/dijetFitResults_FuncType0_nParFit4_MC_1fb-1_Dinko.root --inputBkg /cmshome/gdimperi/Dijet/CMSDIJETrepo/CMSSW_7_2_1_DiJet/src/CMSDIJET/DijetRootTreeAnalyzer/scripts/histo_bkg_mjj.root"
  ####################
  ## gen from fit to data ##
  #cmd_gen = "python create_datacard.py --histpdfSig --fitDat -m "+str(i)+" --lumi 2000 --lumi_in 1769 -n genFit_dataJECV6 --sigEff 1. --sigXS "+str(sigXStimesA[i])+"  -o /cmshome/gdimperi/Dijet/CMSDIJETrepo/CMSSW_7_1_5/src/StatisticalTools/datacards_biasStudy_Spring15/  --inputSig /cmshome/gdimperi/Dijet/CMSDIJETrepo/CMSSW_7_1_5/src/StatisticalTools/inputs/ResonanceShapes_qg_13TeV_PU30_Spring15.root --inputData /cmshome/gdimperi/Dijet/CMSDIJETrepo/CMSSW_7_4_3_Dijet/src/CMSDIJET/DijetRootTreeAnalyzer/scripts/plots_data4T_Run2015D_DCSonly_1769pb-1_JEC_Summer15_25nsV6_withSF/histo_data_mjj_fromTree.root --inputBkg /cmshome/gdimperi/Dijet/CMSDIJETrepo/CMSSW_7_4_3_Dijet/src/CMSDIJET/DijetRootTreeAnalyzer/scripts/plots_data4T_Run2015D_DCSonly_1769pb-1_JEC_Summer15_25nsV6_withSF/histo_data_mjj_fromTree.root"
  ## gen from histogram template QCD ##
  #cmd_gen = "python create_datacard.py --histpdfSig --histpdfBkg -m "+str(i)+" --lumi 2000 --lumi_in 1769 -n genMChist --sigEff 1. --sigXS "+str(sigXStimesA[i])+"  -o /cmshome/gdimperi/Dijet/CMSDIJETrepo/CMSSW_7_1_5/src/StatisticalTools/datacards_biasStudy_Spring15/  --inputSig /cmshome/gdimperi/Dijet/CMSDIJETrepo/CMSSW_7_1_5/src/StatisticalTools/inputs/ResonanceShapes_qg_13TeV_PU30_Spring15.root --inputData /cmshome/gdimperi/Dijet/CMSDIJETrepo/CMSSW_7_4_3_Dijet/src/CMSDIJET/DijetRootTreeAnalyzer/scripts/plots_data4T_Run2015D_DCSonly_1769pb-1_JEC_Summer15_25nsV6_withSF/histo_data_mjj_fromTree.root --inputBkg /cmshome/gdimperi/Dijet/CMSDIJETrepo/CMSSW_7_4_3_Dijet/src/CMSDIJET/DijetRootTreeAnalyzer/scripts/plots_data4T_Run2015D_DCSonly_1769pb-1_JEC_Summer15_25nsV6_withSF/histo_data_mjj_fromTree.root"
  ##MC times slope dataV6/dataV5
  #cmd_gen = "python create_datacard.py --histpdfSig --histpdfBkg -m "+str(i)+" --lumi 2000 --lumi_in 1769 -n genMChist_timesSlope --sigEff 1. --sigXS "+str(sigXStimesA[i])+"  -o /cmshome/gdimperi/Dijet/CMSDIJETrepo/CMSSW_7_1_5/src/StatisticalTools/datacards_biasStudy_Spring15/  --inputSig /cmshome/gdimperi/Dijet/CMSDIJETrepo/CMSSW_7_1_5/src/StatisticalTools/inputs/ResonanceShapes_qg_13TeV_PU30_Spring15.root --inputData /cmshome/gdimperi/Dijet/CMSDIJETrepo/CMSSW_7_4_3_Dijet/src/CMSDIJET/DijetRootTreeAnalyzer/scripts/plots_data4T_Run2015D_DCSonly_1769pb-1_JEC_Summer15_25nsV6_withSF/histo_data_mjj_fromTree.root --inputBkg histo_mjj_forBiasJEC.root"
  ##MC ratio slope dataV6/dataV5
  #cmd_gen = "python create_datacard.py --histpdfSig --histpdfBkg -m "+str(i)+" --lumi 2000 --lumi_in 1769 -n genMChist_ratioSlope --sigEff 1. --sigXS "+str(sigXStimesA[i])+"  -o /cmshome/gdimperi/Dijet/CMSDIJETrepo/CMSSW_7_1_5/src/StatisticalTools/datacards_biasStudy_Spring15/  --inputSig /cmshome/gdimperi/Dijet/CMSDIJETrepo/CMSSW_7_1_5/src/StatisticalTools/inputs/ResonanceShapes_qg_13TeV_PU30_Spring15.root --inputData /cmshome/gdimperi/Dijet/CMSDIJETrepo/CMSSW_7_4_3_Dijet/src/CMSDIJET/DijetRootTreeAnalyzer/scripts/plots_data4T_Run2015D_DCSonly_1769pb-1_JEC_Summer15_25nsV6_withSF/histo_data_mjj_fromTree.root --inputBkg histo_mjj_forBiasJEC.root"
  #cmd_fit = "python create_datacard.py --histpdfSig --fitDat -m "+str(i)+" --lumi 2000 --lumi_in 1769  -n toFit_wideRange --sigEff 1. --sigXS "+str(sigXStimesA[i])+"  -o /cmshome/gdimperi/Dijet/CMSDIJETrepo/CMSSW_7_1_5/src/StatisticalTools/datacards_biasStudy_Spring15/ --inputSig /cmshome/gdimperi/Dijet/CMSDIJETrepo/CMSSW_7_1_5/src/StatisticalTools/inputs/ResonanceShapes_qg_13TeV_PU30_Spring15.root --inputData /cmshome/gdimperi/Dijet/CMSDIJETrepo/CMSSW_7_4_3_Dijet/src/CMSDIJET/DijetRootTreeAnalyzer/scripts/plots_data4T_Run2015D_DCSonly_1769pb-1_JEC_Summer15_25nsV6_withSF/histo_data_mjj_fromTree.root --inputBkg /cmshome/gdimperi/Dijet/CMSDIJETrepo/CMSSW_7_4_3_Dijet/src/CMSDIJET/DijetRootTreeAnalyzer/scripts/plots_data4T_Run2015D_DCSonly_1769pb-1_JEC_Summer15_25nsV6_withSF/histo_data_mjj_fromTree.root"
  ###################
  
  
  print cmd_gen1
  os.system(cmd_gen1)  
  print cmd_gen2
  os.system(cmd_gen2)  
  print cmd_fit
  os.system(cmd_fit)  
